"""empty message

Revision ID: 3276178198a1
Revises: 4286b217a048
Create Date: 2019-12-23 22:39:38.885881

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3276178198a1'
down_revision = '4286b217a048'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_ingredients', sa.Column('measurement_id', sa.Integer(), nullable=True))
    op.drop_constraint('recipe_ingredients_ibfk_2', 'recipe_ingredients', type_='foreignkey')
    op.create_foreign_key(None, 'recipe_ingredients', 'ingredient_measurements', ['measurement_id'], ['id'])
    op.drop_column('recipe_ingredients', 'measurement')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_ingredients', sa.Column('measurement', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'recipe_ingredients', type_='foreignkey')
    op.create_foreign_key('recipe_ingredients_ibfk_2', 'recipe_ingredients', 'ingredient_measurements', ['measurement'], ['id'])
    op.drop_column('recipe_ingredients', 'measurement_id')
    # ### end Alembic commands ###
