"""empty message

Revision ID: 4286b217a048
Revises: 6d1ff699f649
Create Date: 2019-12-23 22:04:03.745130

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4286b217a048'
down_revision = '6d1ff699f649'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient_measurements', sa.Column('description', sa.String(length=60), nullable=True))
    op.create_index(op.f('ix_ingredient_measurements_description'), 'ingredient_measurements', ['description'], unique=False)
    op.drop_index('ix_ingredient_measurements_name', table_name='ingredient_measurements')
    op.drop_column('ingredient_measurements', 'name')
    op.add_column('ingredients', sa.Column('measurement_id', sa.Integer(), nullable=True))
    op.drop_constraint('ingredients_ibfk_1', 'ingredients', type_='foreignkey')
    op.create_foreign_key(None, 'ingredients', 'ingredient_measurements', ['measurement_id'], ['id'])
    op.drop_column('ingredients', 'default_measurement')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('default_measurement', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ingredients', type_='foreignkey')
    op.create_foreign_key('ingredients_ibfk_1', 'ingredients', 'ingredient_measurements', ['default_measurement'], ['id'])
    op.drop_column('ingredients', 'measurement_id')
    op.add_column('ingredient_measurements', sa.Column('name', mysql.VARCHAR(length=60), nullable=True))
    op.create_index('ix_ingredient_measurements_name', 'ingredient_measurements', ['name'], unique=False)
    op.drop_index(op.f('ix_ingredient_measurements_description'), table_name='ingredient_measurements')
    op.drop_column('ingredient_measurements', 'description')
    # ### end Alembic commands ###
